# docker-compose-dev.yml  (place this in project root)
services:
  app:
    container_name: perfectorder-app
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    image: perfectorder:dev-1.00
    ports:
      - "8001:80"
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/perfectorder

  mysql:
    container_name: perfectorder-mysql
    image: mysql:8.0
    env_file:
      - docker/development/mysql/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
