# docker-compose-prod.yml  (place this in project root)
services:
  app:
    container_name: perfectorder-app
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: perfectorder:prod-1.00
    ports:
      - "80:80"
    environment:
      - APP_NAME="Perfect Order"
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=https://perfectorder.shop
      - LOG_CHANNEL=stack
      - DB_HOST=mysql
      - QUEUE_CONNECTION=database
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: perfectorder-mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
